// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include "pxr/base/arch/export.h"

#if defined(OMNI_SCI_FILE_FORMAT_SHARED_STATIC)
#    define OMNI_SCI_FILE_FORMAT_SHARED_API
#    define OMNI_SCI_FILE_FORMAT_SHARED_API_TEMPLATE_CLASS(...)
#    define OMNI_SCI_FILE_FORMAT_SHARED_API_TEMPLATE_STRUCT(...)
#    define OMNI_SCI_FILE_FORMAT_SHARED_TYPE
#    define OMNI_SCI_FILE_FORMAT_SHARED_LOCAL
#else
#    if defined(OMNI_SCI_FILE_FORMAT_SHARED_EXPORTS)
#        define OMNI_SCI_FILE_FORMAT_SHARED_API ARCH_EXPORT
#        define OMNI_SCI_FILE_FORMAT_SHARED_API_TEMPLATE_CLASS(...) ARCH_EXPORT_TEMPLATE(class, __VA_ARGS__)
#        define OMNI_SCI_FILE_FORMAT_SHARED_API_TEMPLATE_STRUCT(...) ARCH_EXPORT_TEMPLATE(struct, __VA_ARGS__)
#    else
#        define OMNI_SCI_FILE_FORMAT_SHARED_API ARCH_IMPORT
#        define OMNI_SCI_FILE_FORMAT_SHARED_API_TEMPLATE_CLASS(...) ARCH_IMPORT_TEMPLATE(class, __VA_ARGS__)
#        define OMNI_SCI_FILE_FORMAT_SHARED_API_TEMPLATE_STRUCT(...) ARCH_IMPORT_TEMPLATE(struct, __VA_ARGS__)
#    endif
#    define OMNI_SCI_FILE_FORMAT_SHARED_TYPE ARCH_EXPORT_TYPE
#    define OMNI_SCI_FILE_FORMAT_SHARED_LOCAL ARCH_HIDDEN
#endif
